
# This is for copy one object from s3 to another s3

name: Deploy to S3
# 'on':
#   push:
#     branches:
#       - main
on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name : Install dependies
        uses : npm install

      - name : create build
        uses : npm run build
      
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AccessKey}}'
          aws-secret-access-key: '${{ secrets.SecretKey}}'
          aws-region: ap-south-1
      - name: Sync build folder to S3 bucket
        run: |
            aws s3 sync ./build s3://yash-bucket-cicd
